version: '3'
services:
  postgresql:
    image: postgis-custom
    build:
      context: postgresql
    environment:
    - POSTGRES_USER=temba
    - POSTGRES_DB=temba
    - POSTGRES_PASSWORD=temba
    volumes:
    - ./postgresql.conf.d:/etc/postgresql/conf.d
  container_registry:
    image: registry:2
    volumes:
    - /var/run/registry2:/var/lib/registry
  registry:
    volumes:
    - ./registry.conf.d:/etc/nginx/conf.d
    build: 
      context: nginx
    image: registry-proxy
    environment:
    - REGISTRY_USERNAME=temba
    - REGISTRY_PASSWORD=temba
    command: [nginx-debug, '-g', 'daemon off;']

